// SPDX-License-Identifier: Apache-2.0
// <auto-generated />
// Generated by eng/generate_shapes.py; do not edit.
import type { Id } from "./gen/arcforges/foundation/v1/foundation_pb.js";
// WHATWG APIs exist in supported Node and browsers; no ambient DOM dependency.
declare const TextEncoder: { new (): { encode(input: string): Uint8Array } };
declare const crypto: { subtle: { digest(algorithm: string, data: Uint8Array): Promise<ArrayBuffer> } };
declare function atob(value: string): string;
/** Closed source-owned completion operation; no arbitrary signing label. */
export enum InstallationInitialOperation { CompleteAuthentication=1, RedeemEmailCode=2, CompleteEnrollment=3, NativeToken=4 }
const labels = ["identity.completeAuthentication", "identity.redeemEmailCode", "identity.completeEnrollment", "native.token"];
const encoder = new TextEncoder();
function id(value: Id | undefined): value is Id & {value: Uint8Array} { return value?.value instanceof Uint8Array && value.value.length===16 && value.value.some(x=>x!==0); }
function join(domain:string,label:string,command:Uint8Array,a:Uint8Array,b:Uint8Array):Uint8Array {
  const prefix=encoder.encode(domain+'\0'),name=encoder.encode(label),output=new Uint8Array(prefix.length+4+name.length+16+64);output.set(prefix);new DataView(output.buffer).setUint32(prefix.length,name.length,false);let n=prefix.length+4;output.set(name,n);n+=name.length;output.set(command,n);n+=16;output.set(a,n);output.set(b,n+32);return output;
}
/** Returns newly owned canonical data or undefined. No signature or permission is produced. */
export function tryInitialSigningData(operation:InstallationInitialOperation,commandId:Id|undefined,challenge:Uint8Array,binding:Uint8Array):Uint8Array|undefined {
  if(!Number.isInteger(operation) || operation<1 || operation>4 || !id(commandId) || !(challenge instanceof Uint8Array) || challenge.length!==32 || !(binding instanceof Uint8Array) || binding.length!==32)return undefined;
  return join('arcforges.installation-possession.v1',labels[operation-1]!,commandId.value,challenge,binding);
}
/** Hashes the decoded canonical token; never returns the token. Private key custody is outside this helper. */
export async function tryRefreshSigningData(commandId:Id|undefined,context:Uint8Array,canonicalRefreshToken:string):Promise<Uint8Array|undefined> {
  if(!id(commandId) || !(context instanceof Uint8Array) || context.length!==32 || typeof canonicalRefreshToken!=='string' || /^[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$/.exec(canonicalRefreshToken)?.[0]!==canonicalRefreshToken)return undefined;
  const capturedCommand=commandId.value.slice(),capturedContext=context.slice(),token=new Uint8Array(32);
  try { const raw=atob(canonicalRefreshToken.replaceAll('-','+').replaceAll('_','/')+'=');if(raw.length!==32)return undefined;for(let i=0;i<32;i++)token[i]=raw.charCodeAt(i);const digest=new Uint8Array(await crypto.subtle.digest('SHA-256',token));return join('arcforges.installation-refresh-possession.v1','identity.refreshSession',capturedCommand,capturedContext,digest); }
  finally {token.fill(0);capturedCommand.fill(0);capturedContext.fill(0);}
}

const maximumInt64=9223372036854775807n, maximumInstant=253402300799999999n;
function integer(value:bigint,minimum:bigint,maximum:bigint=maximumInt64):boolean {
  return typeof value==='bigint' && value>=minimum && value<=maximum;
}
function fixed(value:Uint8Array,length:number):boolean { return value instanceof Uint8Array && value.length===length; }
function zero(value:Uint8Array):boolean { return value.every(byte=>byte===0); }
function text(value:string,maximum:number,empty=false):Uint8Array|undefined {
  if(typeof value!=='string' || !empty && value.length===0 || value.length>maximum)return undefined;
  for(let n=0;n<value.length;n++) {
    const code=value.charCodeAt(n);
    if(code>=0xd800 && code<=0xdbff) { const low=value.charCodeAt(++n); if(!(low>=0xdc00 && low<=0xdfff))return undefined; }
    else if(code>=0xdc00 && code<=0xdfff)return undefined;
  }
  const bytes=encoder.encode(value);return bytes.length<=maximum?bytes:undefined;
}
function field(bytes:Uint8Array):Uint8Array { const output=new Uint8Array(bytes.length+4);new DataView(output.buffer).setUint32(0,bytes.length,false);output.set(bytes,4);return output; }
function signed(value:bigint):Uint8Array { const output=new Uint8Array(8);new DataView(output.buffer).setBigInt64(0,value,false);return output; }
function concatenate(domain:string,parts:readonly Uint8Array[]):Uint8Array {
  const prefix=encoder.encode(domain+'\0'),output=new Uint8Array(prefix.length+parts.reduce((sum,part)=>sum+part.length,0));
  output.set(prefix);let offset=prefix.length;for(const part of parts){output.set(part,offset);offset+=part.length;}return output;
}
function product(value:string):boolean { return value==='arcscope' || value==='companion'; }
function purpose(value:number):boolean { return Number.isInteger(value) && value>=1 && value<=5; }
/** Hashes exact server-owned flow facts. It confers no authentication or installation authority. */
export async function tryFlowBindingHash(realmId:Id|undefined,flowId:Id|undefined,installationId:Id|undefined,
  productId:string,platform:string,publicKeySha256:Uint8Array,keyVersion:bigint,authPurpose:number,authEpoch:bigint,
  recoveryGeneration:bigint,recoveryRevision:bigint,clientId:string,redirectUri:string,pkceChallenge:Uint8Array,
  stateSha256:Uint8Array,expiresAtMicros:bigint):Promise<Uint8Array|undefined> {
  if(!id(realmId)||!id(flowId)||!id(installationId)||!product(productId)||!integer(keyVersion,1n)||!purpose(authPurpose)
    ||!integer(authEpoch,1n)||!integer(recoveryGeneration,0n)||!integer(recoveryRevision,1n)||!integer(expiresAtMicros,1n,maximumInstant)
    ||!fixed(publicKeySha256,32)||!fixed(pkceChallenge,32)||!fixed(stateSha256,32))return undefined;
  const platformBytes=text(platform,128),clientBytes=text(clientId,256,true),redirectBytes=text(redirectUri,2048,true);
  if(platformBytes===undefined || typeof platform!=='string' || /^[A-Za-z0-9._:/-]+$/.exec(platform)?.[0]!==platform
    ||clientBytes===undefined||redirectBytes===undefined||(clientId.length===0)!==(redirectUri.length===0)
    ||clientId.length===0 && (!zero(pkceChallenge)||!zero(stateSha256)))return undefined;
  // All bytes are copied into an owned bounded transcript before the first asynchronous digest.
  const transcript=concatenate('arcforges.installation-flow-binding.v1',[realmId.value,flowId.value,installationId.value,
    field(encoder.encode(productId)),field(platformBytes),publicKeySha256,signed(keyVersion),signed(BigInt(authPurpose)),signed(authEpoch),
    signed(recoveryGeneration),signed(recoveryRevision),field(clientBytes),field(redirectBytes),pkceChallenge,stateSha256,signed(expiresAtMicros)]);
  return new Uint8Array(await crypto.subtle.digest('SHA-256',transcript));
}
/** Hashes only actual current session/install facts. Caller-provided context is never permission. */
export async function tryRefreshContextHash(realmId:Id|undefined,userId:Id|undefined,deviceId:Id|undefined,
  installationId:Id|undefined,sessionId:Id|undefined,familyId:Id|undefined,productId:string,publicKeySha256:Uint8Array,
  keyVersion:bigint,authPurpose:number,authEpoch:bigint,recoveryGeneration:bigint,sessionRevision:bigint,
  familyExpiresAtMicros:bigint):Promise<Uint8Array|undefined> {
  if(!id(realmId)||!id(userId)||!id(deviceId)||!id(installationId)||!id(sessionId)||!id(familyId)||!product(productId)
    ||!fixed(publicKeySha256,32)||!integer(keyVersion,1n)||!purpose(authPurpose)||!integer(authEpoch,1n)
    ||!integer(recoveryGeneration,0n)||!integer(sessionRevision,1n)||!integer(familyExpiresAtMicros,1n,maximumInstant))return undefined;
  const transcript=concatenate('arcforges.installation-refresh-context.v1',[realmId.value,userId.value,deviceId.value,
    installationId.value,sessionId.value,familyId.value,field(encoder.encode(productId)),publicKeySha256,signed(keyVersion),
    signed(BigInt(authPurpose)),signed(authEpoch),signed(recoveryGeneration),signed(sessionRevision),signed(familyExpiresAtMicros)]);
  return new Uint8Array(await crypto.subtle.digest('SHA-256',transcript));
}
