<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
    <PackageId>ArcForges.Contracts.PublicApi</PackageId>
    <Version>1.0.0-ci.0.0</Version>
    <Description>ArcForges public protobuf messages and gRPC bindings. Initial Hello World demonstration.</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>ArcForges;protobuf;grpc;contracts</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <None Include="README.md" Pack="true" PackagePath="/" />
    <None Include="../../LICENSE" Pack="true" PackagePath="/" />
    <None Include="../../../../public/proto/**/*.proto" Pack="true" PackagePath="proto/" />
    <None Include="$(ContractMetadataDir)/*" Pack="true" PackagePath="/"
          Condition="'$(ContractMetadataDir)' != ''" />
  </ItemGroup>
  <PropertyGroup>
    <LicenceBoundary>Apache</LicenceBoundary>
  </PropertyGroup>
</Project>
