# SPDX-License-Identifier: Apache-2.0
"""Offline tests for package-owned generation and lock-bound cache resolution."""
import json
from pathlib import Path
import sys
import tempfile
import unittest
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "eng"))
import contracts


class GenerationRoutes(unittest.TestCase):
    def test_public_route_rejects_private_schema(self):
        with patch("package_catalog.packages", return_value=[
            {"access": "public", "proto": ["internal/proto/arcforges/operator/v1/operator.proto"]}
        ]):
            with self.assertRaisesRegex(ValueError, "private"):
                contracts.generation_packages()

    def test_route_rejects_parent_traversal(self):
        with patch("package_catalog.packages", return_value=[
            {"access": "internal", "proto": ["internal/proto/../../../secret.proto"]}
        ]):
            with self.assertRaisesRegex(ValueError, "Invalid"):
                contracts.generation_packages()

    def test_header_preserves_upstream_and_is_idempotent(self):
        with tempfile.TemporaryDirectory() as directory:
            file = Path(directory) / "sample.cs"
            file.write_bytes(b"// Copyright upstream  \r\n// <auto-generated>\r\nclass X {}\t\r\n\r\n")
            contracts.normalize_generated(file)
            first = file.read_bytes()
            contracts.normalize_generated(file)
            self.assertEqual(first, file.read_bytes())
            self.assertIn(b"// Copyright upstream\n", first)
            self.assertTrue(first.startswith(b"// SPDX-License-Identifier: Apache-2.0\n"))

    def test_cache_requires_exact_lock_integrity(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            cache = root / "cache/grpc.tools/2.84.0"
            cache.mkdir(parents=True)
            lock = root / "eng/Codegen/packages.lock.json"
            lock.parent.mkdir(parents=True)
            lock.write_text(json.dumps({"dependencies": {"net10.0": {"Grpc.Tools": {
                "resolved": "2.84.0", "contentHash": "expected"
            }}}}))
            digest = cache / ".nupkg.metadata"
            with patch.object(contracts, "ROOT", root), patch.dict(contracts.os.environ, {"NUGET_PACKAGES": str(root / "cache")}):
                digest.write_text(json.dumps({"contentHash": "wrong"}))
                with self.assertRaisesRegex(ValueError, "integrity"):
                    contracts.grpc_tools()
                digest.write_text(json.dumps({"contentHash": "expected"}))
                self.assertEqual(cache, contracts.grpc_tools())


if __name__ == "__main__":
    unittest.main()
