<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAotCompatible>true</IsAotCompatible>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/public/dotnet/ArcForges.Contracts.PublicApi/ArcForges.Contracts.PublicApi.csproj" />
    <PackageReference Include="Grpc.Net.Client" />
  </ItemGroup>
  <PropertyGroup>
    <LicenceBoundary>Apache</LicenceBoundary>
  </PropertyGroup>
</Project>
