# SPDX-License-Identifier: Apache-2.0
"""Generate explicit, reflection-free selected contract shape models and checks."""
from __future__ import annotations

import json
import html
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
HEADER = "// SPDX-License-Identifier: Apache-2.0\n// <auto-generated />\n// Generated by eng/generate_shapes.py; do not edit.\n"


def pascal(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in value.split("_"))


def literal(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def emit(path: Path, content: str, check: bool) -> None:
    data = (content.replace("\r\n", "\n").rstrip() + "\n").encode("utf-8")
    if check:
        if not path.is_file() or path.read_bytes() != data:
            raise ValueError(f"Stale generated shape output: {path.relative_to(ROOT)}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)


class JsonShapes:
    """Compile the selected closed JSON-schema subset; unknown constraints fail."""

    def __init__(self, schema: dict, namespace: str):
        self.schema = schema
        self.namespace = namespace
        self.title = schema["title"]
        self.nodes: list[dict] = []
        self.ids: dict[int, int] = {}
        self.cs: list[str] = []
        self.ts: list[str] = []
        self.models: dict[str, dict] = {}

    def resolve(self, node: dict) -> dict:
        if "$ref" not in node:
            return node
        ref = node["$ref"]
        if not ref.startswith("#/$defs/"):
            raise ValueError(f"Only explicit same-schema definition refs are supported: {ref}")
        return self.schema["$defs"][ref.removeprefix("#/$defs/")]

    def visit(self, node: dict) -> int:
        node = self.resolve(node)
        if id(node) in self.ids:
            return self.ids[id(node)]
        index = len(self.nodes)
        self.ids[id(node)] = index
        self.nodes.append(node)
        allowed = {"$schema", "$id", "$defs", "title", "description", "type", "properties", "required",
                   "additionalProperties", "items", "minItems", "maxItems", "minLength", "maxLength",
                   "minimum", "maximum", "pattern", "enum", "const", "not", "x-arcforges-rules", "x-arcforges-schema-version",
                   "x-arcforges-max-bytes", "$comment"}
        unknown = node.keys() - allowed
        if unknown:
            raise ValueError(f"Unimplemented JSON shape constraints: {sorted(unknown)}")
        if node.get("type") == "object":
            if node.get("additionalProperties") is not False:
                raise ValueError("Every generated object must explicitly close additionalProperties")
            for child in node.get("properties", {}).values():
                self.visit(child)
        elif node.get("type") == "array":
            self.visit(node["items"])
        elif node.get("type") not in {"string", "integer", "boolean"}:
            raise ValueError(f"Unsupported JSON shape type: {node.get('type')}")
        return index

    def typename(self, node: dict, ts: bool, hint: str) -> str:
        if "$ref" in node:
            name = node["$ref"].split("/")[-1]
            target = self.resolve(node)
            if target.get("type") == "object":
                self.models[name] = target
                return name
            return self.typename(target, ts, name)
        kind = node["type"]
        if kind == "object":
            name = node.get("title", hint)
            self.models[name] = node
            return name
        if kind == "array":
            return self.typename(node["items"], ts, hint + "Item") + "[]"
        return {"string": "string", "integer": "number" if ts else "long", "boolean": "boolean" if ts else "bool"}[kind]

    def generate(self) -> tuple[str, str, str]:
        self.visit(self.schema)
        self.models[self.title] = self.schema
        model_cs: list[str] = []
        model_ts: list[str] = []
        done: set[str] = set()
        while self.models.keys() - done:
            name = sorted(self.models.keys() - done)[0]
            node = self.models[name]
            done.add(name)
            model_cs.append(f"/// <summary>Generated closed {html.escape(name)} JSON record.</summary>\npublic sealed record {name}\n{{")
            model_ts.append(f"export interface {name} {{")
            for prop, child in node["properties"].items():
                required = prop in node.get("required", [])
                cstype = self.typename(child, False, name + pascal(prop))
                tstype = self.typename(child, True, name + pascal(prop))
                model_cs.append(f"    /// <summary>{'Required' if required else 'Optional'} {html.escape(prop)} field from the authored {html.escape(name)} schema.</summary>\n"
                                f"    [global::System.Text.Json.Serialization.JsonPropertyName({literal(prop)})]\n"
                                f"    public {'required ' if required else ''}{cstype}{'' if required else '?'} {pascal(prop)} {{ get; init; }}")
                model_ts.append(f"  {prop}{'' if required else '?'}: {tstype};")
            model_cs.append("}\n")
            model_ts.append("}\n")
        for index, node in enumerate(self.nodes):
            self.compile_node(index, node)
        cs = HEADER + "#nullable enable\nusing System.Text;\n" + f"namespace {self.namespace};\n\n" + "\n".join(model_cs)
        cs += f"\n/// <summary>Compile-time JSON metadata for the {html.escape(self.title)} schema and its record dependencies.</summary>\n"
        cs += CS_CONTEXT_OPTIONS
        cs += "\n".join(f"[global::System.Text.Json.Serialization.JsonSerializable(typeof({name}))]" for name in sorted(done))
        cs += f"\npublic partial class {self.title}JsonContext : global::System.Text.Json.Serialization.JsonSerializerContext {{ }}\n\n"
        validator_namespace = self.namespace if "CloudInternal" in self.namespace else "ArcForges.Contracts.Validation"
        validator = HEADER + "#nullable enable\nusing System.Text;\n" + f"namespace {validator_namespace};\n\n"
        validator += f"/// <summary>Closed authored-schema validation for {html.escape(self.title)} JSON values.</summary>\npublic static class {self.title}Json\n{{\n"
        validator += "    /// <summary>Checks required fields, declared types, unknown properties and selected profile bounds.</summary>\n    public static bool IsValid(global::System.Text.Json.JsonElement value) => Check0(value);\n"
        validator += self.cs_codec()
        validator += "\n".join(self.cs) + "\n" + CS_JSON_HELPERS + "\n}\n"
        ts = HEADER + "\n".join(model_ts) + f"\nexport function is{self.title}(value: unknown): value is {self.title} {{ return check0(value); }}\n"
        ts += self.ts_codec(sorted(done))
        ts += "\n".join(self.ts) + "\n" + TS_JSON_HELPERS
        return cs, validator, ts

    def max_bytes(self) -> int:
        value = self.schema.get("x-arcforges-max-bytes")
        if type(value) is not int or not 1 <= value <= 4194304:
            raise ValueError(f"{self.title} must declare x-arcforges-max-bytes within the 4 MiB transport bound")
        return value

    def cs_codec(self) -> str:
        record = f"global::{self.namespace}.{self.title}"
        info = f"global::{self.namespace}.{self.title}JsonContext.Default.{self.title}"
        return (CS_CODEC.replace("__RECORD__", record).replace("__INFO__", info)
                .replace("__MAX__", str(self.max_bytes())).replace("__TITLE__", html.escape(self.title)))

    def ts_codec(self, models: list[str]) -> str:
        stem = self.title[:1].lower() + self.title[1:]
        lines = [TS_CODEC.replace("__TITLE__", self.title).replace("__STEM__", stem).replace("__MAX__", str(self.max_bytes()))]
        for name in models:
            node = self.models[name]
            lines.append(f"function order{name}(value: {name}): Record<string, unknown> {{\n  const out: Record<string, unknown> = {{}};")
            for prop, child in node["properties"].items():
                access = f"value[{literal(prop)}]"
                target = self.resolve(child)
                if target.get("type") == "object":
                    child_name = child["$ref"].split("/")[-1] if "$ref" in child else target.get("title", name + pascal(prop))
                    expression = f"order{child_name}({access})"
                elif target.get("type") == "array" and self.resolve(target["items"]).get("type") == "object":
                    items = target["items"]
                    child_name = items["$ref"].split("/")[-1] if "$ref" in items else self.resolve(items).get("title")
                    expression = f"{access}.map(item => order{child_name}(item))"
                else:
                    expression = access
                if prop in node.get("required", []):
                    lines.append(f"  out[{literal(prop)}] = {expression};")
                else:
                    lines.append(f"  if ({access} !== undefined) out[{literal(prop)}] = {expression};")
            lines.append("  return out;\n}")
        return "\n".join(lines) + "\n"

    def compile_node(self, index: int, node: dict) -> None:
        c = [f"    private static bool Check{index}(global::System.Text.Json.JsonElement value)\n    {{"]
        t = [f"function check{index}(value: unknown): boolean {{"]
        kind = node["type"]
        if kind == "object":
            c += ["        if (value.ValueKind != global::System.Text.Json.JsonValueKind.Object) return false;",
                  "        var seen = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal);",
                  "        foreach (var property in value.EnumerateObject())", "        {",
                  "            if (!seen.Add(property.Name)) return false;", "            switch (property.Name)", "            {"]
            t += ["  if (typeof value !== 'object' || value === null || Array.isArray(value)) return false;",
                  "  const object = value as Record<string, unknown>;", "  for (const key of Object.keys(object)) {", "    switch (key) {"]
            for prop, child in node["properties"].items():
                child_id = self.visit(child)
                c.append(f"                case {literal(prop)}: if (!Check{child_id}(property.Value)) return false; break;")
                t.append(f"      case {literal(prop)}: if (!check{child_id}(object[key])) return false; break;")
            c += ["                default: return false;", "            }", "        }"]
            t += ["      default: return false;", "    }", "  }"]
            for prop in node.get("required", []):
                c.append(f"        if (!seen.Contains({literal(prop)})) return false;")
                t.append(f"  if (!Object.prototype.hasOwnProperty.call(object, {literal(prop)})) return false;")
        elif kind == "array":
            child_id = self.visit(node["items"])
            c += ["        if (value.ValueKind != global::System.Text.Json.JsonValueKind.Array) return false;"]
            t += ["  if (!Array.isArray(value)) return false;"]
            for bound, op in [("minItems", "<"), ("maxItems", ">")]:
                if bound in node:
                    c.append(f"        if (value.GetArrayLength() {op} {node[bound]}) return false;")
                    t.append(f"  if (value.length {op} {node[bound]}) return false;")
            c.append(f"        foreach (var item in value.EnumerateArray()) if (!Check{child_id}(item)) return false;")
            t.append(f"  if (!value.every(item => check{child_id}(item))) return false;")
        elif kind == "string":
            c += ["        if (value.ValueKind != global::System.Text.Json.JsonValueKind.String) return false;", "        var text = value.GetString()!;", "        if (!ValidText(text)) return false;"]
            t += ["  if (typeof value !== 'string' || !validText(value)) return false;"]
            for bound, op in [("minLength", "<"), ("maxLength", ">")]:
                if bound in node:
                    c.append(f"        if (ScalarLength(text) {op} {node[bound]}) return false;")
                    t.append(f"  if ([...value].length {op} {node[bound]}) return false;")
            if "pattern" in node:
                # Nonbacktracking with an explicit timeout; patterns remain authored inputs.
                c.append(f"        if (!Matches(text, {literal(node['pattern'])})) return false;")
                t.append(f"  if ((new RegExp({literal(node['pattern'])}, 'u')).exec(value)?.[0] !== value) return false;")
            values = node.get("enum", [node["const"]] if "const" in node else None)
            if values is not None:
                c.append("        if (" + " && ".join(f"text != {literal(v)}" for v in values) + ") return false;")
                t.append("  if (" + " && ".join(f"value !== {literal(v)}" for v in values) + ") return false;")
            if "not" in node:
                if set(node["not"]) != {"const"} or not isinstance(node["not"]["const"], str):
                    raise ValueError("Only not/const string exclusion is selected")
                c.append(f"        if (text == {literal(node['not']['const'])}) return false;")
                t.append(f"  if (value === {literal(node['not']['const'])}) return false;")
        elif kind == "integer":
            c += ["        if (value.ValueKind != global::System.Text.Json.JsonValueKind.Number || !value.TryGetInt64(out var number)) return false;"]
            t += ["  if (typeof value !== 'number' || !Number.isSafeInteger(value)) return false;"]
            for bound, op in [("minimum", "<"), ("maximum", ">")]:
                if bound in node:
                    c.append(f"        if (number {op} {node[bound]}L) return false;")
                    t.append(f"  if (value {op} {node[bound]}) return false;")
        elif kind == "boolean":
            c += ["        if (value.ValueKind is not (global::System.Text.Json.JsonValueKind.True or global::System.Text.Json.JsonValueKind.False)) return false;"]
            t += ["  if (typeof value !== 'boolean') return false;"]
        rules = node.get("x-arcforges-rules", [])
        for rule in rules:
            if rule in {"inventoryPaths", "inventoryBounds", "inventory"}:
                c.append("        if (!InventoryRules(value)) return false;")
                t.append("  if (!inventoryRules(value)) return false;")
            elif rule in {"uint64", "uint64String"}:
                c.append("        if (!global::System.UInt64.TryParse(text, global::System.Globalization.NumberStyles.None, global::System.Globalization.CultureInfo.InvariantCulture, out _)) return false;")
                t.append("  if (BigInt(value as string) > 18446744073709551615n) return false;")
            elif rule in {"int64", "positiveInt64String"}:
                c.append("        if (!global::System.Int64.TryParse(text, global::System.Globalization.NumberStyles.AllowLeadingSign, global::System.Globalization.CultureInfo.InvariantCulture, out _)) return false;")
                t.append("  if (BigInt(value as string) < -9223372036854775808n || BigInt(value as string) > 9223372036854775807n) return false;")
                if rule == "positiveInt64String":
                    c.append("        if (text.StartsWith('0') || text.StartsWith('-')) return false;")
                    t.append("  if (BigInt(value as string) <= 0n) return false;")
            elif rule == "nonzeroUuid":
                c.append('        if (text == "00000000-0000-0000-0000-000000000000") return false;')
                t.append("  if (value === '00000000-0000-0000-0000-000000000000') return false;")
            else:
                raise ValueError(f"Unimplemented shape rule {rule}")
        c += ["        return true;", "    }"]
        t += ["  return true;", "}"]
        self.cs.append("\n".join(c))
        self.ts.append("\n".join(t))


CS_CONTEXT_OPTIONS = '''[global::System.Text.Json.Serialization.JsonSourceGenerationOptions(
    AllowDuplicateProperties = false,
    AllowTrailingCommas = false,
    DefaultIgnoreCondition = global::System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
    MaxDepth = 32,
    NumberHandling = global::System.Text.Json.Serialization.JsonNumberHandling.Strict,
    ReadCommentHandling = global::System.Text.Json.JsonCommentHandling.Disallow,
    RespectNullableAnnotations = true,
    RespectRequiredConstructorParameters = true,
    UnmappedMemberHandling = global::System.Text.Json.Serialization.JsonUnmappedMemberHandling.Disallow,
    WriteIndented = false)]
'''

CS_CODEC = r'''    /// <summary>The schema's declared UTF-8 document bound in bytes.</summary>
    public const int MaxBytes = __MAX__;
    /// <summary>The maximum JSON container depth, counting the root.</summary>
    public const int MaxDepth = 32;

    /// <summary>Parses one strict __TITLE__ document or throws a typed refusal.</summary>
    public static __RECORD__ Parse(global::System.ReadOnlyMemory<byte> utf8)
        => TryParse(utf8, out var value, out var failure) ? value! : throw new global::ArcForges.Contracts.Foundation.Serialization.ContractSerializationException(failure);

    /// <summary>Checks the byte bound, UTF-8 without BOM, syntax, depth and duplicate properties, then the closed schema, before generated deserialization.</summary>
    public static bool TryParse(global::System.ReadOnlyMemory<byte> utf8, out __RECORD__? value,
        out global::ArcForges.Contracts.Foundation.Serialization.ContractSerializationFailure failure)
    {
        value = null;
        failure = global::ArcForges.Contracts.Foundation.Serialization.ContractSerializationFailure.Malformed;
        if (utf8.Length > MaxBytes)
        {
            failure = global::ArcForges.Contracts.Foundation.Serialization.ContractSerializationFailure.TooLarge;
            return false;
        }
        if (utf8.Span.StartsWith("\xEF\xBB\xBF"u8) || !global::System.Text.Unicode.Utf8.IsValid(utf8.Span)) return false;
        global::System.Text.Json.JsonDocument document;
        try { document = global::System.Text.Json.JsonDocument.Parse(utf8, DocumentOptions); }
        catch (global::System.Text.Json.JsonException) { return false; }
        using (document)
        {
            bool valid;
            // Escaped lone surrogates are syntactically JSON but cannot become text.
            try { valid = IsValid(document.RootElement); }
            catch (global::System.InvalidOperationException) { return false; }
            failure = global::ArcForges.Contracts.Foundation.Serialization.ContractSerializationFailure.Invalid;
            if (!valid) return false;
            try { value = global::System.Text.Json.JsonSerializer.Deserialize(document.RootElement, __INFO__); }
            catch (global::System.Text.Json.JsonException) { return false; }
        }
        if (value is null) return false;
        failure = default;
        return true;
    }

    /// <summary>Writes compact UTF-8 through the generated metadata and refuses output the schema rejects.</summary>
    public static byte[] Serialize(__RECORD__ value)
    {
        global::System.ArgumentNullException.ThrowIfNull(value);
        var bytes = global::System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(value, __INFO__);
        if (!TryParse(bytes, out _, out var failure))
            throw new global::ArcForges.Contracts.Foundation.Serialization.ContractSerializationException(failure);
        return bytes;
    }

    private static readonly global::System.Text.Json.JsonDocumentOptions DocumentOptions = new()
    {
        AllowDuplicateProperties = false,
        AllowTrailingCommas = false,
        CommentHandling = global::System.Text.Json.JsonCommentHandling.Disallow,
        MaxDepth = MaxDepth,
    };

'''

TS_CODEC = r'''
/** The schema's declared UTF-8 document bound in bytes. */
export const __STEM__JsonMaxBytes = __MAX__;

/** Parses one strict __TITLE__ document; refusal kinds match the C# codec. */
export function tryParse__TITLE__Json(input: Uint8Array | string):
  { ok: true; value: __TITLE__ } | { ok: false; failure: "tooLarge" | "malformed" | "invalid" } {
  const parsed = strictJson(input, __MAX__);
  if (!parsed.ok) return parsed;
  return is__TITLE__(parsed.value) ? { ok: true, value: parsed.value } : { ok: false, failure: "invalid" };
}

/** Parses one strict __TITLE__ document or throws an error carrying the refusal kind. */
export function parse__TITLE__Json(input: Uint8Array | string): __TITLE__ {
  const result = tryParse__TITLE__Json(input);
  if (!result.ok) throw Object.assign(new Error(`__TITLE__ JSON refused: ${result.failure}.`), { failure: result.failure });
  return result.value;
}

/** Writes compact UTF-8 in schema property order and refuses output the schema rejects. */
export function serialize__TITLE__Json(value: __TITLE__): Uint8Array {
  const bytes = new TextEncoder().encode(JSON.stringify(order__TITLE__(value)));
  const result = tryParse__TITLE__Json(bytes);
  if (!result.ok) throw Object.assign(new Error(`__TITLE__ JSON refused: ${result.failure}.`), { failure: result.failure });
  return bytes;
}
'''

CS_JSON_HELPERS = r'''
    private static bool Matches(string value, string pattern)
    {
        var match = global::System.Text.RegularExpressions.Regex.Match(value, pattern, global::System.Text.RegularExpressions.RegexOptions.CultureInvariant | global::System.Text.RegularExpressions.RegexOptions.NonBacktracking, global::System.TimeSpan.FromMilliseconds(100));
        return match.Success && match.Index == 0 && match.Length == value.Length;
    }
    private static bool ValidText(string value)
    {
        for (var i = 0; i < value.Length; i++)
        {
            if (char.IsHighSurrogate(value[i])) { if (++i == value.Length || !char.IsLowSurrogate(value[i])) return false; }
            else if (char.IsLowSurrogate(value[i])) return false;
        }
        return true;
    }
    private static int ScalarLength(string text)
    {
        var count = 0;
        foreach (var rune in text.EnumerateRunes()) { _ = rune; count++; }
        return count;
    }
    private static bool InventoryRules(global::System.Text.Json.JsonElement value)
    {
        if (!value.TryGetProperty("files", out var files)) return false;
        var paths = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.OrdinalIgnoreCase);
        string? previous = null;
        ulong total = 0;
        foreach (var file in files.EnumerateArray())
        {
            var path = file.GetProperty("path").GetString()!;
            if (!SafePath(path) || !paths.Add(path) || (previous is not null && global::System.StringComparer.Ordinal.Compare(previous, path) >= 0)) return false;
            if (!global::System.UInt64.TryParse(file.GetProperty("size").GetString(), global::System.Globalization.NumberStyles.None, global::System.Globalization.CultureInfo.InvariantCulture, out var size) || size > 134217728UL) return false;
            total += size;
            if (total > 1073741824UL) return false;
            previous = path;
        }
        return paths.Contains("manifest.json") && files.EnumerateArray().Any(file => file.GetProperty("path").GetString() == "manifest.json");
    }
    private static bool SafePath(string path)
    {
        if (path.Length == 0 || path.Equals("inventory.json", global::System.StringComparison.OrdinalIgnoreCase) || path.Equals("signature.json", global::System.StringComparison.OrdinalIgnoreCase)) return false;
        foreach (var segment in path.Split('/'))
        {
            if (segment.Length == 0 || segment is "." or ".." || segment.EndsWith('.')) return false;
            foreach (var c in segment) if (!(c is >= 'a' and <= 'z' or >= 'A' and <= 'Z' or >= '0' and <= '9' or '_' or '-' or '.')) return false;
            var basename = segment.Split('.')[0].ToUpperInvariant();
            if (basename is "CON" or "PRN" or "AUX" or "NUL" || (basename.Length == 4 && (basename.StartsWith("COM", global::System.StringComparison.Ordinal) || basename.StartsWith("LPT", global::System.StringComparison.Ordinal)) && basename[3] is >= '1' and <= '9')) return false;
        }
        return true;
    }
'''

TS_JSON_HELPERS = r'''
// WHATWG encoding APIs exist in every supported runtime; declared locally so no DOM/Node typings are required.
declare const TextEncoder: { new (): { encode(input: string): Uint8Array } };
declare const TextDecoder: { new (label: string, options: { fatal: boolean; ignoreBOM: boolean }): { decode(input: Uint8Array): string } };

type StrictJsonResult = { ok: true; value: unknown } | { ok: false; failure: "tooLarge" | "malformed" };

/** Strict UTF-8 JSON: no BOM, comments, trailing commas or duplicate properties; depth <= 32; integer lexemes only. */
function strictJson(input: Uint8Array | string, maxBytes: number): StrictJsonResult {
  let text: string;
  if (typeof input === "string") {
    if (!validText(input)) return { ok: false, failure: "malformed" };
    if (new TextEncoder().encode(input).byteLength > maxBytes) return { ok: false, failure: "tooLarge" };
    text = input;
  } else {
    if (input.byteLength > maxBytes) return { ok: false, failure: "tooLarge" };
    try { text = new TextDecoder("utf-8", { fatal: true, ignoreBOM: true }).decode(input); }
    catch { return { ok: false, failure: "malformed" }; }
  }
  try { return { ok: true, value: new StrictJsonReader(text).document() }; }
  catch { return { ok: false, failure: "malformed" }; }
}

class StrictJsonReader {
  private index = 0;
  constructor(private readonly text: string) {}
  document(): unknown {
    this.space();
    const value = this.value(0);
    this.space();
    if (this.index !== this.text.length) throw new SyntaxError("Trailing JSON content");
    return value;
  }
  private value(depth: number): unknown {
    switch (this.text[this.index]) {
      case "{": return this.object(depth + 1);
      case "[": return this.array(depth + 1);
      case '"': return this.string();
      case "t": return this.literal("true", true);
      case "f": return this.literal("false", false);
      case "n": return this.literal("null", null);
      default: return this.number();
    }
  }
  private object(depth: number): Record<string, unknown> {
    if (depth > 32) throw new SyntaxError("JSON depth exceeded");
    this.index++;
    const out: Record<string, unknown> = {};
    const keys = new Set<string>();
    this.space();
    if (this.text[this.index] === "}") { this.index++; return out; }
    for (;;) {
      this.space();
      if (this.text[this.index] !== '"') throw new SyntaxError("Expected property name");
      const key = this.string();
      if (keys.has(key)) throw new SyntaxError("Duplicate JSON property");
      keys.add(key);
      this.space();
      if (this.text[this.index++] !== ":") throw new SyntaxError("Expected colon");
      this.space();
      // defineProperty keeps names such as __proto__ as ordinary own properties.
      Object.defineProperty(out, key, { value: this.value(depth), enumerable: true, writable: true, configurable: true });
      this.space();
      const next = this.text[this.index++];
      if (next === "}") return out;
      if (next !== ",") throw new SyntaxError("Expected comma");
    }
  }
  private array(depth: number): unknown[] {
    if (depth > 32) throw new SyntaxError("JSON depth exceeded");
    this.index++;
    const out: unknown[] = [];
    this.space();
    if (this.text[this.index] === "]") { this.index++; return out; }
    for (;;) {
      this.space();
      out.push(this.value(depth));
      this.space();
      const next = this.text[this.index++];
      if (next === "]") return out;
      if (next !== ",") throw new SyntaxError("Expected comma");
    }
  }
  private string(): string {
    this.index++;
    let out = "";
    for (;;) {
      const c = this.text[this.index++];
      if (c === undefined) throw new SyntaxError("Unterminated string");
      if (c === '"') break;
      if (c < " ") throw new SyntaxError("Unescaped control character");
      if (c !== "\\") { out += c; continue; }
      const e = this.text[this.index++];
      const simple: Record<string, string> = { '"': '"', "\\": "\\", "/": "/", b: "\b", f: "\f", n: "\n", r: "\r", t: "\t" };
      if (e !== undefined && e in simple) { out += simple[e]; continue; }
      if (e !== "u" || !/^[0-9a-fA-F]{4}$/.test(this.text.slice(this.index, this.index + 4))) throw new SyntaxError("Invalid escape");
      out += String.fromCharCode(parseInt(this.text.slice(this.index, this.index + 4), 16));
      this.index += 4;
    }
    if (!validText(out)) throw new SyntaxError("Lone surrogate escape");
    return out;
  }
  private number(): number {
    const match = /-?(?:0|[1-9][0-9]*)(\.[0-9]+)?([eE][+-]?[0-9]+)?/y;
    match.lastIndex = this.index;
    const found = match.exec(this.text);
    if (found === null) throw new SyntaxError("Invalid JSON value");
    this.index = match.lastIndex;
    // Selected schemas have no fractional numbers; fraction/exponent lexemes never satisfy an integer.
    return found[1] !== undefined || found[2] !== undefined ? Number.NaN : Number(found[0]);
  }
  private literal<T>(word: string, value: T): T {
    if (this.text.slice(this.index, this.index + word.length) !== word) throw new SyntaxError("Invalid JSON literal");
    this.index += word.length;
    return value;
  }
  private space(): void {
    while (this.text[this.index] === " " || this.text[this.index] === "\t" || this.text[this.index] === "\n" || this.text[this.index] === "\r") this.index++;
  }
}

function validText(value: string): boolean {
  for (const scalar of value) { const point = scalar.codePointAt(0)!; if (point >= 0xd800 && point <= 0xdfff) return false; }
  return true;
}
function inventoryRules(value: unknown): boolean {
  const files = (value as {files: {path: string; size: string}[]}).files;
  const seen = new Set<string>();
  let previous: string | undefined;
  let total = 0n;
  for (const file of files) {
    const path = file.path;
    const folded = path.toUpperCase();
    if (path.length === 0 || folded === 'INVENTORY.JSON' || folded === 'SIGNATURE.JSON' || seen.has(folded) || (previous !== undefined && previous >= path)) return false;
    for (const segment of path.split('/')) {
      if (!/^[A-Za-z0-9_.-]+$/.test(segment) || segment === '.' || segment === '..' || segment.endsWith('.') || /^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\.|$)/i.test(segment)) return false;
    }
    const size = BigInt(file.size);
    if (size > 134217728n) return false;
    total += size;
    if (total > 1073741824n) return false;
    seen.add(folded);
    previous = path;
  }
  return files.some(file => file.path === 'manifest.json');
}
'''


def generate(check: bool = False) -> None:
    mappings = [
        ("public/http/v1/schema.json", "ArcForges.Contracts.PublicApi.Http.V1", "src/public/dotnet/ArcForges.Contracts.PublicApi", "src/public/ts/api-client"),
        ("public/http/v1/inventory.schema.json", "ArcForges.Sdk.Contracts.Inventory.V1", "src/public/dotnet/ArcForges.Sdk.Contracts", "src/public/ts/api-client"),
        ("internal/ai-http/v1/schema.json", "ArcForges.Contracts.CloudInternal.Http.V1", "src/internal/dotnet/ArcForges.Contracts.CloudInternal", "src/internal/ts/ai-internal"),
    ]
    tsoutputs: dict[str, list[str]] = {}
    for source, namespace, csroot, tsroot in mappings:
        schema = json.loads((ROOT / source).read_text(encoding="utf-8"))
        generated_cs, generated_validator, generated_ts = JsonShapes(schema, namespace).generate()
        name = schema["title"]
        emit(ROOT / csroot / "Generated/Shapes" / (name + ".g.cs"), generated_cs, check)
        validator_root = csroot if "CloudInternal" in namespace else "src/public/dotnet/ArcForges.Contracts.Validation"
        emit(ROOT / validator_root / "Generated/Shapes" / (name + "Validator.g.cs"), generated_validator, check)
        tsoutputs.setdefault(tsroot, []).append(generated_ts)
    for tsroot, contents in tsoutputs.items():
        # Separate module scopes avoid helper/name collisions while preserving one public entry.
        names = []
        for source, namespace, csroot, target in mappings:
            if target == tsroot:
                names.append(json.loads((ROOT / source).read_text(encoding="utf-8"))["title"])
        for name, content in zip(names, contents, strict=True):
            emit(ROOT / tsroot / "src/shapes/gen" / (name + ".ts"), content, check)
        emit(ROOT / tsroot / "src/gen/http.ts", HEADER + "".join(f'export * from "../shapes/gen/{name}.js";\n' for name in names), check)
    generate_proto_checks(check)


def generate_proto_checks(check: bool) -> None:
    messages: dict[str, dict] = {}
    public: set[str] = set()
    for visibility in ["public", "internal"]:
        sidecar = json.loads((ROOT / visibility / "proto/constraints.json").read_text(encoding="utf-8"))
        if sidecar["schemaVersion"] != "proto-constraints.v1":
            raise ValueError("Unknown proto constraint version")
        for fqname, constraints in sidecar["messages"].items():
            messages[fqname] = {"constraints": constraints, "visibility": visibility}
            if visibility == "public":
                public.add(fqname)
    for path in [*(ROOT / "public/proto").rglob("*.proto"), *(ROOT / "internal/proto").rglob("*.proto")]:
        source = re.sub(r"//[^\n]*", "", path.read_text(encoding="utf-8"))
        package = re.search(r"package\s+([\w.]+)\s*;", source)[1]
        for match in re.finditer(r"message\s+(\w+)\s*\{", source):
            fqname = package + "." + match[1]
            if fqname not in messages:
                if package != "arcforges.hello.v1":
                    raise ValueError(f"Missing authored constraints for {fqname}")
                continue
            depth, end = 1, match.end()
            while depth:
                depth += (source[end] == "{") - (source[end] == "}")
                end += 1
            body = source[match.end():end - 1]
            oneofs = {}
            for group in re.finditer(r"oneof\s+(\w+)\s*\{([^}]+)\}", body):
                for field in re.finditer(r"[\w.]+\s+(\w+)\s*=", group[2]):
                    oneofs[field[1]] = group[1]
            fields = {}
            for field in re.finditer(r"(?:(optional|repeated)\s+)?([\w.]+)\s+(\w+)\s*=\s*(\d+)(?:\s*\[([^]]+)\])?\s*;", body):
                label, kind, name, tag, options = field.groups()
                jsonname = re.search(r'json_name\s*=\s*"([^"]+)"', options or "")
                key = jsonname[1] if jsonname else name.split("_")[0] + "".join(pascal(v) for v in name.split("_")[1:])
                resolved = kind.lstrip(".") if "." in kind else package + "." + kind
                fields[key] = {"name": pascal(name), "type": kind, "message": resolved if resolved in messages else None,
                               "label": label, "oneof": oneofs.get(name), "tag": int(tag)}
            if set(fields) != set(messages[fqname]["constraints"]["fields"]):
                raise ValueError(f"Constraint field inventory does not match {fqname}")
            messages[fqname]["fields"] = fields
    groups = [("ArcForges.Contracts.Validation", "src/public/dotnet/ArcForges.Contracts.Validation", public)]
    internal_roots: dict[str, set[str]] = {}
    for name, info in messages.items():
        if info["visibility"] == "internal":
            cstype = info["constraints"]["csharpType"]
            project = cstype.split(".V1.")[0]
            if ".CloudInternal." in project:
                project = "ArcForges.Contracts.CloudInternal"
            internal_roots.setdefault(project, set()).add(name)
    for project, names in internal_roots.items():
        closure = set(names)
        pending = list(names)
        while pending:
            for field in messages[pending.pop()]["fields"].values():
                dependency = field["message"]
                if dependency and dependency not in closure:
                    closure.add(dependency)
                    pending.append(dependency)
        groups.append((project + ".Shapes", "src/internal/dotnet/" + project, closure))
    for namespace, directory, names in groups:
        methods = [proto_cs(name, messages) for name in sorted(names)]
        content = HEADER + "#nullable enable\nusing System.Text;\n" + f"namespace {namespace};\n\n/// <summary>Explicit protobuf shape checks generated from the authored field constraints.</summary>\npublic static class ContractShapeValidation\n{{\n"
        from foundation_semantics import COMMON_CS_HELPERS, CS_HELPERS
        content += "\n".join(methods) + CS_PROTO_HELPERS + COMMON_CS_HELPERS
        if any(n.startswith("arcforges.publicapi.") for n in names):
            content += CS_HELPERS
        content += "\n}\n"
        emit(ROOT / directory / "Generated/Shapes/ProtoValidation.g.cs", content, check)
    # Public protobuf-es checks intentionally exclude extension/private protocols.
    for directory, names in [("src/public/ts/proto", {n for n in public if not n.startswith("arcforges.extensions.")}),
                             ("src/internal/ts/operator-client", next((g[2] for g in groups if g[0] == "ArcForges.Contracts.CloudInternal.Shapes"), set()))]:
        from foundation_semantics import TS_HELPERS, ts_imports
        emit(ROOT / directory / "src/shapes/gen/proto.ts", HEADER + ts_imports(names) + "\n".join(proto_ts(name, messages) for name in sorted(names)) + TS_PROTO_HELPERS + TS_HELPERS, check)


def proto_cs(name: str, messages: dict) -> str:
    from foundation_semantics import cs_rules
    info = messages[name]
    profile = info["constraints"]
    cstype = "global::" + profile["csharpType"]
    lines = [f"    /// <summary>Checks the declared wire/profile constraints of {html.escape(name)}.</summary>",
             f"    public static bool IsValid([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] {cstype}? value) => Check(value, new ValidationContext());",
             f"    private static bool Check([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] {cstype}? value, ValidationContext context)", "    {",
             "        if (value is null || !context.Enter(value)) return false;", "        try", "        {"]
    for fieldname, rules in profile["fields"].items():
        field = info["fields"][fieldname]
        prop = "value." + field["name"]
        message = field["message"]
        repeated = field["label"] == "repeated"
        optional = field["label"] == "optional"
        if rules.get("required") and not repeated:
            if message:
                lines.append(f"        if ({prop} is null) return false;")
            elif optional:
                lines.append(f"        if (!value.Has{field['name']}) return false;")
        # A required message already has a fail-fast null check. Rechecking it in
        # a conditional block weakens flow after the branch joins; validate it
        # directly and retain the Check(true) non-null postcondition instead.
        guard = f"value.Has{field['name']}" if optional else f"{prop} is not null" if message and not repeated and not rules.get("required") else None
        if field["oneof"]:
            guard = f"(int)value.{pascal(field['oneof'])}Case == {field['tag']}"
        inner = []
        if repeated:
            for key, op in [("minItems", "<"), ("maxItems", ">")]:
                if key in rules:
                    inner.append(f"if ({prop}.Count {op} {rules[key]}) return false;")
            if rules.get("unique"):
                inner.append(f"if ({prop}.Distinct().Count() != {prop}.Count) return false;")
            inner.append(f"foreach (var item in {prop})\n        {{")
            inner.extend("    " + item for item in cs_field_checks("item", field, rules.get("items", {})))
            inner.append("}")
        else:
            inner.extend(cs_field_checks(prop, field, rules))
        if guard:
            lines += [f"        if ({guard})", "        {"] + ["            " + line for line in inner] + ["        }"]
        else:
            lines.extend("        " + line for line in inner)
    for group in profile.get("oneofRequired", []):
        lines.append(f"        if ((int)value.{pascal(group)}Case == 0) return false;")
    rules = {
        "nonzeroId": "if (!Nonzero(value.Value)) return false;",
        "canonicalDecimal": "if (!CanonicalDecimal(value.Value)) return false;",
        "committedRevision": "if (value.Revision is not { Value: > 0 }) return false;",
        "exclusiveRevision": "if ((value.ExpectedRev is null ? 0 : 1) + (value.ExpectedLocal is null ? 0 : 1) + (value.ExpectedNative is null ? 0 : 1) > 1) return false;",
        "chunkOffsets": "if (value.Offset > ulong.MaxValue - (ulong)value.Bytes.Length || value.NextOffset != value.Offset + (ulong)value.Bytes.Length) return false;",
        **cs_rules,
    }
    for rule in profile.get("rules", []):
        if rule not in rules:
            raise ValueError(f"Unimplemented proto rule {rule}")
        lines.append("        " + rules[rule])
    lines += ["        return true;", "        }", "        finally { context.Exit(value); }", "    }"]
    return "\n".join(lines)


def cs_field_checks(prop: str, field: dict, rules: dict) -> list[str]:
    known = {"required", "min", "max", "minLength", "maxLength", "bytesLength", "pattern", "enumValues", "maxUtf8Bytes", "items", "finite", "minItems", "maxItems", "unique"}
    if rules.keys() - known:
        raise ValueError(f"Unsupported proto field rules {rules.keys() - known}")
    result = []
    kind = field["type"]
    if field["message"]:
        result.append(f"if (!Check({prop}, context)) return false;")
    if kind == "string":
        result.append(f"if (!ValidUnicode({prop})) return false;")
    if kind in {"double", "float"}:
        result.append(f"if (!{kind}.IsFinite({prop})) return false;")
    if "bytesLength" in rules:
        result.append(f"if ({prop}.Length != {rules['bytesLength']}) return false;")
    for key, op in [("min", "<"), ("max", ">")]:
        if key in rules:
            suffix = "UL" if kind == "uint64" else "L" if kind in {"int64", "sint64"} else "D" if kind == "double" else "F" if kind == "float" else ""
            result.append(f"if ({prop} {op} {rules[key]}{suffix}) return false;")
    for key, op in [("minLength", "<"), ("maxLength", ">")]:
        if key in rules:
            size = f"ScalarLength({prop})" if kind == "string" else prop + ".Length"
            result.append(f"if ({size} {op} {rules[key]}) return false;")
    if "maxUtf8Bytes" in rules:
        result.append(f"if (global::System.Text.Encoding.UTF8.GetByteCount({prop}) > {rules['maxUtf8Bytes']}) return false;")
    if "pattern" in rules:
        result.append(f"if (!Matches({prop}, {literal(rules['pattern'])})) return false;")
    if "enumValues" in rules:
        numeric = all(type(v) is int for v in rules["enumValues"])
        target = f"(int){prop}" if numeric and kind not in {"uint32", "int32", "sint32", "uint64", "int64", "sint64"} else prop
        result.append("if (" + " && ".join(f"{target} != {json.dumps(v)}" for v in rules["enumValues"]) + ") return false;")
    return result


def proto_ts(name: str, messages: dict) -> str:
    from foundation_semantics import ts_rules
    info = messages[name]
    profile = info["constraints"]
    simple = name.split(".")[-1]
    lines = [f"export function is{simple}(input: unknown): boolean {{ return check{simple}(input, {{active: new Set<object>(), depth: 0}}); }}",
             f"function check{simple}(input: unknown, context: ValidationContext): boolean {{",
             "  if (typeof input !== 'object' || input === null || Array.isArray(input) || context.depth >= 100 || context.active.has(input)) return false;",
             "  context.active.add(input); context.depth++;", "  try {", "  const value = input as Record<string, unknown>;"]
    groups: dict[str, list[str]] = {}
    for fieldname, rules in profile["fields"].items():
        field = info["fields"][fieldname]
        if field["oneof"]:
            groups.setdefault(field["oneof"], []).append(fieldname)
            prop = f"(value.{field['oneof']} as {{value: unknown}}).value"
            lines.append(f"  if ((value.{field['oneof']} as {{case?: string}} | undefined)?.case === {literal(fieldname)}) {{")
        else:
            prop = "value." + fieldname
            if rules.get("required") or field["label"] == "repeated":
                lines.append(f"  if ({prop} === undefined) return false;")
            lines.append(f"  if ({prop} !== undefined) {{")
        lines.append(f"    const fieldValue = {prop};")
        prop = "fieldValue"
        repeated = field["label"] == "repeated"
        if repeated:
            lines += [f"    if (!Array.isArray({prop})) return false;"]
            for key, op in [("minItems", "<"), ("maxItems", ">")]:
                if key in rules:
                    lines.append(f"    if ({prop}.length {op} {rules[key]}) return false;")
            if rules.get("unique"):
                lines.append(f"    if (new Set({prop}).size !== {prop}.length) return false;")
            lines.append(f"    for (const item of {prop}) {{")
        lines.extend("    " + line for line in ts_field_checks("item" if repeated else prop, field, rules.get("items", {}) if repeated else rules))
        if repeated:
            lines.append("    }")
        lines.append("  }")
    for group, members in groups.items():
        lines.append(f"  if (value.{group} === undefined || typeof value.{group} !== 'object' || value.{group} === null) return false;")
        options = [literal(v) for v in members]
        if group not in profile.get("oneofRequired", []):
            options.append("undefined")
        lines.append("  if (" + " && ".join(f"(value.{group} as {{case?: string}}).case !== {o}" for o in options) + ") return false;")
    special = {
        "nonzeroId": "if (!(value.value as Uint8Array).some(v => v !== 0)) return false;",
        "canonicalDecimal": "if (!canonicalDecimal(value.value as string)) return false;",
        "committedRevision": "if ((value.revision as {value: bigint}).value <= 0n) return false;",
        "exclusiveRevision": "if ([value.expectedRev, value.expectedLocal, value.expectedNative].filter(v => v !== undefined).length > 1) return false;",
        "chunkOffsets": "if ((value.offset as bigint) + BigInt((value.bytes as Uint8Array).length) > 18446744073709551615n || value.nextOffset !== (value.offset as bigint) + BigInt((value.bytes as Uint8Array).length)) return false;",
        **ts_rules,
    }
    lines.extend("  " + special[rule] for rule in profile.get("rules", []))
    lines += ["  return true;", "  } finally { context.depth--; context.active.delete(input); }", "}"]
    return "\n".join(lines)


def ts_field_checks(prop: str, field: dict, rules: dict) -> list[str]:
    kind = field["type"]
    result = []
    if field["message"]:
        return [f"if (!check{field['message'].split('.')[-1]}({prop}, context)) return false;"]
    bigint = kind in {"uint64", "int64", "sint64"}
    if kind == "bytes":
        result.append(f"if (!({prop} instanceof Uint8Array)) return false;")
    else:
        typename = "bigint" if bigint else "string" if kind == "string" else "boolean" if kind == "bool" else "number"
        result.append(f"if (typeof {prop} !== {literal(typename)}) return false;")
        if typename == "number":
            if kind in {"double", "float"}:
                result.append(f"if (!Number.isFinite({prop}){f' || Math.abs({prop}) > 3.4028234663852886e38' if kind == 'float' else ''}) return false;")
            else:
                result.append(f"if (!Number.isInteger({prop}) || {prop} < {'0' if kind == 'uint32' else '-2147483648'} || {prop} > {'4294967295' if kind == 'uint32' else '2147483647'}) return false;")
        if kind == "string":
            result.append(f"if (!validUnicode({prop})) return false;")
    if bigint:
        lower, upper = ("0n", "18446744073709551615n") if kind == "uint64" else ("-9223372036854775808n", "9223372036854775807n")
        result.append(f"if ({prop} < {lower} || {prop} > {upper}) return false;")
    for key, op in [("min", "<"), ("max", ">")]:
        if key in rules:
            result.append(f"if ({prop} {op} {rules[key]}{'n' if bigint else ''}) return false;")
    for key, op in [("bytesLength", "!=="), ("minLength", "<"), ("maxLength", ">")]:
        if key in rules:
            size = f"[...{prop}].length" if kind == "string" else prop + ".length"
            result.append(f"if ({size} {op} {rules[key]}) return false;")
    if "pattern" in rules:
        result.append(f"if ((new RegExp({literal(rules['pattern'])}, 'u')).exec({prop})?.[0] !== {prop}) return false;")
    if "maxUtf8Bytes" in rules:
        result.append(f"if (utf8Length({prop}) > {rules['maxUtf8Bytes']}) return false;")
    if "enumValues" in rules:
        result.append("if (" + " && ".join(f"{prop} !== {json.dumps(v)}" for v in rules["enumValues"]) + ") return false;")
    return result


CS_PROTO_HELPERS = r'''
    private sealed class ValidationContext
    {
        private readonly global::System.Collections.Generic.HashSet<object> active = new(global::System.Collections.Generic.ReferenceEqualityComparer.Instance);
        public bool Enter(object value) => active.Count < 100 && active.Add(value);
        public void Exit(object value) => active.Remove(value);
    }
    private static bool ValidUnicode(string text)
    {
        for (var i = 0; i < text.Length; i++)
        {
            if (!char.IsSurrogate(text[i])) continue;
            if (!char.IsHighSurrogate(text[i]) || ++i >= text.Length || !char.IsLowSurrogate(text[i])) return false;
        }
        return true;
    }

    private static bool Matches(string value, string pattern)
    {
        var match = global::System.Text.RegularExpressions.Regex.Match(value, pattern, global::System.Text.RegularExpressions.RegexOptions.CultureInvariant | global::System.Text.RegularExpressions.RegexOptions.NonBacktracking, global::System.TimeSpan.FromMilliseconds(100));
        return match.Success && match.Index == 0 && match.Length == value.Length;
    }
    private static bool Nonzero(global::Google.Protobuf.ByteString value)
    {
        foreach (var item in value) if (item != 0) return true;
        return false;
    }
    private static int ScalarLength(string text)
    {
        var count = 0;
        foreach (var rune in text.EnumerateRunes()) { _ = rune; count++; }
        return count;
    }
    private static bool CanonicalDecimal(string value)
    {
        if (!Matches(value, "^-?(0|[1-9][0-9]*)(\\.[0-9]{1,9})?$")) return false;
        if (value.StartsWith('-') && !value.Any(c => c is >= '1' and <= '9')) return false;
        var digits = value.Replace("-", "", global::System.StringComparison.Ordinal).Replace(".", "", global::System.StringComparison.Ordinal).TrimStart('0');
        return digits.Length <= 28;
    }
'''

TS_PROTO_HELPERS = r'''
type ValidationContext = {active: Set<object>; depth: number};
function validUnicode(text: string): boolean {
  for (let i = 0; i < text.length; i++) {
    const unit = text.charCodeAt(i);
    if (unit < 0xd800 || unit > 0xdfff) continue;
    if (unit > 0xdbff || ++i >= text.length) return false;
    const low = text.charCodeAt(i);
    if (low < 0xdc00 || low > 0xdfff) return false;
  }
  return true;
}

function canonicalDecimal(value: string): boolean {
  if (/^-?(0|[1-9][0-9]*)(\.[0-9]{1,9})?$/.exec(value)?.[0] !== value) return false;
  if (value.startsWith('-') && !/[1-9]/.test(value)) return false;
  return value.replace(/[-.]/g, '').replace(/^0+/, '').length <= 28;
}
function utf8Length(value: string): number {
  let size = 0;
  for (const scalar of value) {
    const point = scalar.codePointAt(0)!;
    size += point <= 0x7f ? 1 : point <= 0x7ff ? 2 : point <= 0xffff ? 3 : 4;
  }
  return size;
}
'''
