# SPDX-License-Identifier: Apache-2.0
"""Export independent public fixture data without leaking internal vectors."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate(check: bool = False) -> None:
    fixtures = {path.name: json.loads(path.read_text(encoding="utf-8"))
                for path in sorted((ROOT / "fixtures/public").glob("*.json"))}
    if not fixtures:
        raise ValueError("Public fixture package cannot be empty")
    content = ("// SPDX-License-Identifier: Apache-2.0\n"
               "// Generated by eng/generate_fixtures.py from fixtures/public. Do not edit.\n"
               "export const publicFixtures = " + json.dumps(fixtures, indent=2, ensure_ascii=True)
               + " as const;\n")
    target = ROOT / "src/public/ts/contract-fixtures/src/index.ts"
    if check:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            raise ValueError("Stale public fixture package")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")
