# SPDX-License-Identifier: Apache-2.0
"""Emit immutable public authorization metadata after checking compiled descriptors.

No production operation is inferred from generated client code. Authored shards own
authorization, and the bounded existing FileDescriptorSet reader checks transport
coverage. Operator, private/helper, in-process and HTTP-exception rows stay out.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from check_compatibility import descriptor
from check_operation_scope import EXAMPLES, audit, require
from package_catalog import packages

ROOT = Path(__file__).resolve().parents[1]
OWNERS = {"ArcForges.Contracts.PublicApi": "PublicOperationCatalog",
          "ArcForges.Contracts.Events": "EventOperationCatalog"}
HEADER = "// SPDX-License-Identifier: Apache-2.0\n// Generated by ArcForges Contracts; do not edit.\n#nullable enable\n"


def project(report: dict, owners: list[dict], models: dict[str, dict]) -> dict[str, list[dict]]:
    """Require one public metadata row for every owned compiled business method."""
    require({row["id"] for row in owners} == set(OWNERS), "exact public catalog package owners required")
    source_owners, compiled = {}, {}
    for owner in owners:
        require(owner["kind"] == "nuget" and owner["access"] == "public", "public NuGet owner required")
        methods = {}
        model = models[owner["id"]]
        for source in owner["proto"]:
            require(source.startswith("public/proto/"), "catalog source outside public proto")
            require(source not in source_owners, "ambiguous catalog source owner")
            source_owners[source] = owner["id"]
            filename = source.removeprefix("public/proto/")
            require(filename in model["files"], "missing compiled catalog source: " + source)
            for service, service_methods in model["files"][filename]["services"].items():
                for method in service_methods:
                    binding = service.removeprefix(".") + "/" + method
                    if EXAMPLES.get(binding) == source:
                        continue
                    require(binding not in methods, "duplicate compiled catalog binding")
                    methods[binding] = source
        compiled[owner["id"]] = methods
    output = {owner: [] for owner in OWNERS}
    seen_ids, seen_bindings = set(), set()
    for row in report["operations"]:
        if row.get("status") != "registered" or row.get("surface") != "public":
            continue
        require(row.get("kind") == "proto", "non-proto operation claims public business surface")
        operation, binding, source = row["operationId"], row["binding"], row["source"]
        require(operation not in seen_ids, "duplicate public catalog operation: " + operation)
        require(binding not in seen_bindings, "duplicate public catalog binding: " + binding)
        require(source in source_owners, "unowned or nonpublic catalog source: " + source)
        owner = source_owners[source]
        require(compiled[owner].get(binding) == source, "metadata/compiled descriptor mismatch: " + binding)
        seen_ids.add(operation)
        seen_bindings.add(binding)
        output[owner].append(row)
    for owner, rows in output.items():
        require({row["binding"] for row in rows} == set(compiled[owner]),
                "missing public catalog metadata for compiled owner: " + owner)
        rows.sort(key=lambda row: row["operationId"])
    return output


def literal(value) -> str:
    require(value is None or type(value) in {bool, str}, "unsupported operation catalog literal")
    return json.dumps(value, ensure_ascii=False)


def value_source(value) -> tuple[str, str]:
    if isinstance(value, dict):
        require(set(value) == {"from"} and isinstance(value["from"], str), "unsupported derived catalog value")
        return "null", literal(value["from"])
    return literal(value), "null"


def render(owner: str, rows: list[dict]) -> str:
    entries = []
    for row in rows:
        auth = row["authorization"]
        risk, risk_source = value_source(auth["risk"])
        step, step_source = value_source(auth["stepUp"])
        presence, presence_source = value_source(auth["localPresence"])
        args = [*(literal(row[key]) for key in ("operationId", "binding", "scope", "idempotency", "profile", "sourceRule")),
                literal(auth["capability"]), risk, risk_source, literal(auth["approval"]), step, step_source,
                presence, presence_source, literal(auth["egress"]), literal(auth["patEligible"]),
                "[" + ", ".join(literal(actor) for actor in auth["actorKinds"]) + "]"]
        entries.append("        new(" + ", ".join(args) + "),\n")
    name = OWNERS[owner]
    return (HEADER + "using System.Collections.Frozen;\nusing System.Diagnostics.CodeAnalysis;\n"
            "using ArcForges.Contracts.PublicApi.Operations;\n\n"
            + f"namespace {owner}.Operations;\n\n"
            "/// <summary>Generated immutable public business authorization facts, checked against compiled service descriptors.</summary>\n"
            + f"public static class {name}\n{{\n"
            "    /// <summary>All operations owned by this package, in ordinal operation-ID order.</summary>\n"
            "    public static IReadOnlyList<PublicOperationPolicy> All { get; } = Array.AsReadOnly<PublicOperationPolicy>(\n"
            "    [\n" + "".join(entries) + "    ]);\n\n"
            "    private static readonly FrozenDictionary<string, PublicOperationPolicy> ById =\n"
            "        All.ToFrozenDictionary(operation => operation.OperationId, StringComparer.Ordinal);\n\n"
            "    /// <summary>Finds an exact case-sensitive operation ID. Unknown IDs return false; nothing is inferred or registered.</summary>\n"
            "    public static bool TryGet(string operationId, [NotNullWhen(true)] out PublicOperationPolicy? policy)\n"
            "    {\n        ArgumentNullException.ThrowIfNull(operationId);\n"
            "        return ById.TryGetValue(operationId, out policy);\n    }\n}\n")


def emit(path: Path, content: str, check: bool) -> None:
    data = content.encode("utf-8")
    if check:
        require(path.is_file() and path.read_bytes() == data, "stale generated operation catalog: " + str(path))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)


def generate(check: bool = False, root: Path = ROOT) -> None:
    owners = [row for row in packages("nuget", root) if row["id"] in OWNERS]
    models = {owner["id"]: descriptor((root / "artifacts" / owner["descriptor"]).read_bytes()) for owner in owners}
    rows = project(audit(root), owners, models)
    for owner in owners:
        emit(root / owner["sourceRoot"] / "Generated/Operations" / (OWNERS[owner["id"]] + ".g.cs"),
             render(owner["id"], rows[owner["id"]]), check)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generate(arguments.check)
