<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" GeneratePathProperty="true" />
  </ItemGroup>
  <PropertyGroup>
    <LicenceBoundary>Apache</LicenceBoundary>
  </PropertyGroup>
</Project>
