// SPDX-License-Identifier: Apache-2.0
// <auto-generated />
// Generated by eng/generate_shapes.py; do not edit.
package io.github.arcforges.contracts

import io.github.arcforges.contracts.foundation.v1.Id
import io.github.arcforges.contracts.publicapi.v1.AuthPurpose
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CharacterCodingException
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets
import java.security.MessageDigest
import java.util.Base64

/** Closed native completion operation. No caller-selected signing label exists. */
enum class InstallationInitialOperation(val wire: Int) { CompleteAuthentication(1), RedeemEmailCode(2), CompleteEnrollment(3), NativeToken(4) }

/** Pure canonical public data; no key custody, signature or authentication result. */
object InstallationPossession {
    private val labels = arrayOf("identity.completeAuthentication", "identity.redeemEmailCode", "identity.completeEnrollment", "native.token")
    private fun validId(value: Id?): Boolean = value != null && value.hasValue() && value.value.size() == 16 && value.value.toByteArray().any { it.toInt() != 0 }
    private fun join(domain: String, label: String, command: ByteArray, a: ByteArray, b: ByteArray): ByteArray {
        val prefix=(domain+"\u0000").toByteArray(StandardCharsets.UTF_8); val name=label.toByteArray(StandardCharsets.UTF_8)
        return ByteBuffer.allocate(prefix.size+4+name.size+16+64).order(ByteOrder.BIG_ENDIAN).put(prefix).putInt(name.size).put(name).put(command).put(a).put(b).array()
    }
    fun tryInitialSigningData(operation: InstallationInitialOperation?, commandId: Id?, challenge: ByteArray, binding: ByteArray): ByteArray? {
        if(operation==null || !validId(commandId) || challenge.size!=32 || binding.size!=32) return null
        return join("arcforges.installation-possession.v1", labels[operation.wire-1], commandId!!.value.toByteArray(), challenge, binding)
    }
    fun tryRefreshSigningData(commandId: Id?, context: ByteArray, canonicalRefreshToken: String): ByteArray? {
        if(!validId(commandId) || context.size!=32 || !Regex("[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]").matches(canonicalRefreshToken))return null
        val token=try { Base64.getUrlDecoder().decode(canonicalRefreshToken) } catch(_: IllegalArgumentException) {return null}
        try {
            if(token.size!=32 || Base64.getUrlEncoder().withoutPadding().encodeToString(token)!=canonicalRefreshToken)return null
            return join("arcforges.installation-refresh-possession.v1", "identity.refreshSession", commandId!!.value.toByteArray(), context, MessageDigest.getInstance("SHA-256").digest(token))
        } finally {token.fill(0)}
    }

    private const val maximumInstant = 253402300799999999L
    private fun text(value: String?, maximum: Int, empty: Boolean = false): ByteArray? {
        if(value == null || !empty && value.isEmpty() || value.length > maximum) return null
        return try {
            val encoded = StandardCharsets.UTF_8.newEncoder().onMalformedInput(CodingErrorAction.REPORT)
                .onUnmappableCharacter(CodingErrorAction.REPORT).encode(CharBuffer.wrap(value))
            if(encoded.remaining() > maximum) null else ByteArray(encoded.remaining()).also { encoded.get(it) }
        } catch(_: CharacterCodingException) { null }
    }
    private fun field(bytes: ByteArray): ByteArray = ByteBuffer.allocate(bytes.size+4).order(ByteOrder.BIG_ENDIAN).putInt(bytes.size).put(bytes).array()
    private fun signed(value: Long): ByteArray = ByteBuffer.allocate(8).order(ByteOrder.BIG_ENDIAN).putLong(value).array()
    private fun transcript(domain: String, vararg parts: ByteArray): ByteArray {
        val prefix=(domain+"\u0000").toByteArray(StandardCharsets.UTF_8)
        val output=ByteBuffer.allocate(prefix.size+parts.sumOf { it.size }).order(ByteOrder.BIG_ENDIAN).put(prefix)
        parts.forEach { output.put(it) };return output.array()
    }
    private fun purpose(value: AuthPurpose?): Int? = when(value) {
        null, AuthPurpose.UNRECOGNIZED -> null
        else -> value.number.takeIf { it in 1..5 }
    }
    /** Hashes original factual owner binding only; no key or authorization is returned. */
    fun tryFlowBindingHash(realmId: Id?, flowId: Id?, installationId: Id?, productId: String?, platform: String?,
        publicKeySha256: ByteArray, keyVersion: Long, authPurpose: AuthPurpose?, authEpoch: Long, recoveryGeneration: Long,
        recoveryRevision: Long, clientId: String?, redirectUri: String?, pkceChallenge: ByteArray, stateSha256: ByteArray,
        expiresAtMicros: Long): ByteArray? {
        val purpose=purpose(authPurpose) ?: return null
        if(!validId(realmId)||!validId(flowId)||!validId(installationId)||productId !in listOf("arcscope","companion")
            ||publicKeySha256.size!=32||keyVersion<=0||authEpoch<=0||recoveryGeneration<0||recoveryRevision<=0
            ||pkceChallenge.size!=32||stateSha256.size!=32||expiresAtMicros<=0||expiresAtMicros>maximumInstant)return null
        val platformBytes=text(platform,128) ?: return null
        val clientBytes=text(clientId,256,true) ?: return null
        val redirectBytes=text(redirectUri,2048,true) ?: return null
        if(!Regex("[A-Za-z0-9._:/-]+").matches(platform!!) || clientId!!.isEmpty()!=redirectUri!!.isEmpty()
            ||clientId.isEmpty() && (pkceChallenge.any { it.toInt()!=0 } || stateSha256.any { it.toInt()!=0 }))return null
        val data=transcript("arcforges.installation-flow-binding.v1",realmId!!.value.toByteArray(),flowId!!.value.toByteArray(),
            installationId!!.value.toByteArray(),field(text(productId,128)!!),field(platformBytes),publicKeySha256,
            signed(keyVersion),signed(purpose.toLong()),signed(authEpoch),signed(recoveryGeneration),signed(recoveryRevision),
            field(clientBytes),field(redirectBytes),pkceChallenge,stateSha256,signed(expiresAtMicros))
        return MessageDigest.getInstance("SHA-256").digest(data)
    }
    /** Uses real current session/install facts; the result itself never authorizes refresh. */
    fun tryRefreshContextHash(realmId: Id?, userId: Id?, deviceId: Id?, installationId: Id?, sessionId: Id?, familyId: Id?,
        productId: String?, publicKeySha256: ByteArray, keyVersion: Long, authPurpose: AuthPurpose?, authEpoch: Long,
        recoveryGeneration: Long, sessionRevision: Long, familyExpiresAtMicros: Long): ByteArray? {
        val purpose=purpose(authPurpose) ?: return null
        if(!validId(realmId)||!validId(userId)||!validId(deviceId)||!validId(installationId)||!validId(sessionId)||!validId(familyId)
            ||productId !in listOf("arcscope","companion")||publicKeySha256.size!=32||keyVersion<=0||authEpoch<=0
            ||recoveryGeneration<0||sessionRevision<=0||familyExpiresAtMicros<=0||familyExpiresAtMicros>maximumInstant)return null
        val data=transcript("arcforges.installation-refresh-context.v1",realmId!!.value.toByteArray(),userId!!.value.toByteArray(),
            deviceId!!.value.toByteArray(),installationId!!.value.toByteArray(),sessionId!!.value.toByteArray(),familyId!!.value.toByteArray(),
            field(text(productId,128)!!),publicKeySha256,signed(keyVersion),signed(purpose.toLong()),signed(authEpoch),
            signed(recoveryGeneration),signed(sessionRevision),signed(familyExpiresAtMicros))
        return MessageDigest.getInstance("SHA-256").digest(data)
    }
}
